app.name=HelpDesk System
db.url=jdbc:mysql://localhost:3306/helpdesk_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
db.username=root
db.password=
db.pool.maxSize=10
mail.enabled=true
mail.fromName=HelpDesk System
mail.from=
mail.replyTo=no-reply@helpdesk.local
mail.password=
mail.host=smtp.gmail.com
mail.port=587
mail.starttls=true
